### ISSUE TITLE
Open Datasheet Errata

### ISSUE THREAD

**Issue by technobly** [particle-iot/docs#19]
> Datasheet errata will be added to this issue when found.  Datasheets will be updated with the listed version after items are checked off.  Some errata may persist between revisions, and they will be moved up to the next proposed revision.
# E Series Datasheet (v002) - Not Released Yet
- [ ] Mention the use of optional SPI FLASH and the associated GPIO dependencies.
- [ ] Clarify on the use of the GND pads on the bottom
- [ ] Mention operation in below 0C temperatures for LiPo batteries

# Photon Datasheet (v016)
- [x] Updated External Coexistence Interface section (currently unsupported)

# P1 Datasheet (v010)
- [x] Change "Paid tiers of Particle Cloud start when you create a product with more than 25 devices" to say "Particle provides free access to the Particle Cloud for prototyping and paid tiers for production".
- [x] Updated External Coexistence Interface section (currently unsupported)

# P1 Datasheet (v009)
- [x] Added part number for 1MB external SPI flash (MX25L8006E)

# P1 Datasheet (v008)
- [x] EEPROM emulation bank 2 (64 KB) - remove only 16k used
- [x] Replace STM32 pin names with Particle/Wiring API names to keep everything intuitive and high level.  Leave STM32 pin numbers for deep dives. #545
- [x] Make Image of P1 Block Diagram Snazzy
- [x] CAN bus pins should be noted as 3.3V tolerant (technically they are 5V tolerant on the RX but since you wouldn't operate them with a 5V transceiver it's proper to classify them as 3.3V)
- [x] Fix and clarify pin descriptions https://github.com/spark/docs/pull/399 (make sure to review P1 and Photon datasheets as well)
- [x] Add note to clarify why MICRO_SPI1_SS is not hooked up to DAC/A6 (PA4) https://github.com/spark/docs/issues/469
- [x] update DCT Layout https://docs.particle.io/datasheets/p1-datasheet/#dct-layout notably adding radio_flags, and any other new sections.
- [x] JTAG pin P1 module number is wrong.  "D4	JTAG_TDO PB3 54 MICRO_JTAG_TDO Floating" should be "D4 JTAG_TDO PB3 52 MICRO_JTAG_TDO Floating"  (54 -> 52)
- [x] Add warning about powering the Photon from long wires on USB and VIN, and give advice on what components can be added externally to mitigate this.  From Richtek datasheet:

> When a ceramic capacitor is used at the input and the power is supplied by a wall adapter through long wires, a load step at the output can induce ringing at the input, VIN. At best, this ringing can couple to the output and be mistaken as loop instability. At worst, a sudden inrush of current through the long wires can potentially cause a voltage spike at VIN large enough to damage the part

# Photon Datasheet (v015)
- [x] EEPROM emulation bank 2 (64 KB) - remove only 16k used
- [x] Add link to power pin limits. #556 
- [x] Replace STM32 pin names with Particle/Wiring API names to keep everything intuitive and high level.  Leave STM32 pin numbers for deep dives. #545
- [x] Memory Map: Rename device_id to device_code and add device_id to DCT layout
- [x] CAN bus pins should be noted as 3.3V tolerant (technically they are 5V tolerant on the RX but since you wouldn't operate them with a 5V transceiver it's proper to classify them as 3.3V)
- [x] Fix and clarify pin descriptions https://github.com/spark/docs/pull/399 (make sure to review P1 and Photon datasheets as well)
- [x] update DCT Layout https://docs.particle.io/datasheets/photon-datasheet/#dct-layout notably adding radio_flags, and any other new sections.
- [x] Add warning about powering the Photon from long wires on USB and VIN, and give advice on what components can be added externally to mitigate this.  From Richtek datasheet:

> When a ceramic capacitor is used at the input and the power is supplied by a wall adapter through long wires, a load step at the output can induce ringing at the input, VIN. At best, this ringing can couple to the output and be mistaken as loop instability. At worst, a sudden inrush of current through the long wires can potentially cause a voltage spike at VIN large enough to damage the part

# Electron Datasheet (v005)
- [x] Replace STM32 pin names with Particle/Wiring API names to keep everything intuitive and high level.  Leave STM32 pin numbers for deep dives. #545 
- [x] How to power the Electron without a battery.
- [x] Describe the usage of the VBAT to 3V3 bridge on the bottom. Update link to instructions for removing VBAT to 3V3 jumper located here: https://docs.particle.io/datasheets/electron-datasheet/#pin-markings- and here are some rough draft instructions: https://community.particle.io/t/electron-power-leak-from-vbat/21312/5
- [x] Electron Charging LED: But what is the "appropriate firmware command"? https://github.com/spark/docs/issues/326
- [x] Change Vin and Iin parameters to Vvin and Ivin to be more clear
- [x] EEPROM emulation bank 2 (64 KB) - remove only 16k used
- [x] v002 of the Pinout PDF has an error in the lower left of the Legend, UART4 and UART5 should be Serial4 and Serial5, not Serial2 and Serial3.
- [x] CAN bus pins should be noted as 3.3V tolerant (technically they are 5V tolerant on the RX but since you wouldn't operate them with a 5V transceiver it's proper to classify them as 3.3V)
- [x] Memory Map: for v0.6.0-rc.1 and later has 3 system parts and re-ordering (1,2,3 is now 2,1,3).
- [x] update DCD Layout https://docs.particle.io/datasheets/electron-datasheet/#dcd-layout notably adding radio_flags, and any other new sections.

# P1 Datasheet (v007)
- [x] Add new spare pin P1S6 to pinout, PWM list, pin description, update TESTMODE description, etc.. https://github.com/spark/firmware/pull/1120 Branch added here: https://github.com/spark/docs/tree/feature/p1-datasheet-v007/p1s6

# Electron Datasheet (v004)
- [x] Replace some copy/paste errors in STM32 part number in Electron datasheet copied from Photon datasheet.  Replace all STM32F205RGY6 with STM32F205RGT6.
- [x] Add full STM32F205RGT6 part number to every mention of STM32 in datasheet.

# Photon Datasheet (v014)
- [x] Updated list of Mating Connectors

# Electron Datasheet (v003)
- [x] Fix and clarify pin descriptions https://github.com/spark/docs/pull/399 (make sure to review P1 and Photon datasheets as well)
- [x] ERROR in Operating Current (Cellular OFF) IINavg 2-15mA, it should be IINavg 47-50mA
- [x] Updated list of Mating Connectors

# P1 Datasheet (v006)
- [x] Update P1 pin listing: TESTMODE pin 33 (PA8), connected to MCO1 by default, outputs 32kHz clock for WICED powersave mode - currently unsupported for user control.

# Electron Datasheet (v002)
- [x] Add size of Electron SIM card **Nano (4FF)** to all places in where SIM is referenced in the datasheet.  Also include a link to a [comparison of sizes](https://en.wikipedia.org/wiki/Subscriber_identity_module#Formats).
- [x] Add [memory map](https://github.com/spark/firmware/wiki/Electron-Memory-Map) to datasheet, high level DCD view with link to the API for DCD: (use https://github.com/spark/docs/issues/82 as reference as well)
- [x] Add explanation of power inputs/outputs (PMIC/USB/VIN/Li+/3V3/3V8), and add this warning: It is not recommended to feed the Electron's 3V3 node with an external 3.3V source. Only use this 3V3 pin as an output for supporting circuitry.
- [x] Add DAC output limits: min resistive load is 5k ohms, and max capacitive load is 50pF.
- [x] SWD pin locations
- [x] Pinout diagram could use clarification, see #310 
- [x] Rework block diagram to remove the dot-junction for VUSB and STM32F205, they are not connected.  Only the two data lines are connected.  https://docs.particle.io/datasheets/electron-datasheet/#block-diagram
- [x] Clean-up Recommended Operating Conditions Table https://github.com/spark/docs/issues/325

# Photon Datasheet (v013)
- [x] Update Block Diagram to show VBAT broken out separately from the 3.3V supply https://docs.particle.io/datasheets/photon-datasheet/#block-diagram
- [x] Add full STM32F205RGY6 part number to the datasheet.
- [x] Change Vin and Iin parameters to Vvin and Ivin to be more clear
- [x] <s>Update BT COEX section with link to example of how to control as GPIO, or add a note as note supported.</s>Remove reference to using BT COEX pins as GPIO, this is not currently practical.
- [x] Add memory map to datasheet, high level DCD view with link to the API for DCD: https://github.com/spark/docs/issues/82
- [x] Add max source/sink current for I/Os, and total (each I/O is 25mA and total is 120mA)
- [x] Add SWD mode hookups to the JTAG info: https://community.particle.io/t/connections-for-st-link-v2-mini-jtag/16659
- [x] "Typical current consumption is 80mA with a 3.3V input. Deep sleep quiescent current is 160uA. " OLD INFO (SEE recommended operating conditions instead)
- [x] Add a section for test points, and point out where in the datasheet they are referenced. https://github.com/spark/docs/issues/223
- [x] Add known errata link that points back to this issue, which will be updated in the future with new issues found in the datasheet.
- [x] Add DAC output limits: min resistive load is 5k ohms, and max capacitive load is 50pF.
- [x] clarified note about routing signals under the Photon's antenna

# P1 Datasheet (v005)
- [x] Pinout image 3, RESET button pin is 34 (MICRO_RST_N), not 26.
- [x] Add full STM32F205RGY6 part number to the datasheet.
- [x] <s>Update BT COEX section with link to example of how to control as GPIO, or add a note as note supported.</s>Remove reference to using BT COEX pins as GPIO, this is not currently practical.
- [x] Add memory map to datasheet, high level DCT view with link to the API for DCT: https://github.com/spark/docs/issues/82
- [x] Add max source/sink current for I/Os, and total (each I/O is 25mA and total is 120mA)
- [x] Add SWD mode hookups to the JTAG info: https://community.particle.io/t/connections-for-st-link-v2-mini-jtag/16659
- [x] Add note about 5V @ VIN for P1, this is in reference to when the SMPS shown in the Reference Design is implemented and current is measured from the VIN node shown on the schematic: https://docs.particle.io/datasheets/p1-datasheet/#recommended-operating-conditions-i-class-icon-check-i-
- [x] "Typical current consumption is 80mA with a 3.3V input. Deep sleep quiescent current is 160uA. " OLD INFO (SEE recommended operating conditions instead)
- [x] Add known errata link that points back to this issue, which will be updated in the future with new issues found in the datasheet.
- [x] Change all references to "Spare1-6" to "P1S0" - "P1S5"
- [x] Add dimension info for TAPE: https://docs.particle.io/datasheets/-datasheet/#tape-and-reel-info
- [x] Add DAC output limits: min resistive load is 5k ohms, and max capacitive load is 50pF.
- [x] clarified note about routing signals under the P1's antenna

# Photon Datasheet (v012)
- [x] Added some information for TELEC certification stuff

# Photon Datasheet (v011)
- [x] Add FCC IC CE Warnings and End Product Labeling Requirements, Update power output
- [x] Minor fix to section 3.2: A0~A9 should be A0~A7.  Description is correct.
- [x] Section 3.2: Mention of A5 should be A3.  Also call out DAC1 as A6.  Can also be used as A3, and A6 in software.
- [x] Add extra pin numbers to the land pattern (25 - 31) and ref. to section 3 of the datasheet.
- [x] Fix RGB led part number on BOM: https://community.particle.io/t/photon-rgb-led-bom-and-footprint-dont-match/12973

# Photon Datasheet (v010)
- [x] Update VBAT info.

# Photon Datasheet (v009)
- [x] Remove RX and TX as ADCs.
- [x] Add DAC as an ADC channel 4 to the pinout diagrams and text.
- [x] DAC1 and DAC2 are both 12-bit, not 10-bit.
- [x] Fix height dimensions:
  Should be:
  With    1.44 x 0.8 x 0.27 (36.58 x 20.32 x 6.86)    5 grams
  Without 1.44 x 0.8 x 0.17 (36.58 x 20.32 x 4.32)    3.7 grams
- [x] Update quiescent current (80uA typical, 100uA max)

# Photon Datasheet (v008)
- [x] Replace "Spark" with "Particle"
- [x] Add lead-free logo
- [x] Add Ordering information section (just points to store)
- [x] Add FCC ID, IC ID and FCC and CE logos
- [x] Replace the packaging image with a better quality one

# PØ Datasheet (v002) - Not Released Yet
- [ ] Image of PØ with pin numbers
- [ ] Image of PØ with dimensions
- [ ] Image of PØ module dimensions
- [ ] Image of PØ module land pattern (and solder mask size)
- [ ] Image of PØ Tape with Dimensions, Orientation and Feed Direction
- [x] Images of Reference Design Schematic
- [x] Images of Reference Design PCB
- [x] Image of colorful pinouts (use Photon's)
- [x] Image of Power Connections
- [x] Image of PØ module (vector) for cover page.
- [x] Image of PØ Block Diagram
- [x] Replace "Spark" with "Particle"
- [ ] Change github.com/spark to github.com/particleio
- [ ] Change Spark.lbr to Particle.lbr
- [x] Text for all sections

# P1 Datasheet (v004)
- [x] Pin number 54 is used twice in pin mapping table. A0 / GPIO14 is pin 50 and not 54
- [x] Fold in any corrections made to Photon Datasheet.
- Evaluation of this report:
- [x] JTAG: The schematic shows the Photon instead of the P1. Also, I was wondering if I need to breakout the Broadcom JTAG pins as well.
- [x] 2.6 External Coexistence Interface: I guess this text is from the Photon. I don't have a P1 in-hand yet so I can only guess based on pictures but aren't the coexistence signals routed to regular pads on the bottom of the module, unlike yours on the Photon? Accordingly, the table should show the P1 pin numbers as 57, 56, 58.
- [x] 3.2 Pin Description (DAC): I think DAC2 is A3 instead of A5.

# P1 Datasheet (v003)
- [x] Update VBAT_MICRO info

# P1 Datasheet (v002)
- [x] Image of P1 with pin numbers
- [x] Image of P1 with dimensions
- [x] Image of P1 module dimensions
- [x] Image of P1 module land pattern (and solder mask size)
- [x] Image of P1 Tape with Dimensions, Orientation and Feed Direction
- [x] Images of Reference Design Schematic
- [x] Image of colorful pinouts (use Photon's, add extra pins)
- [x] Image of Power Connections
- [x] Image of P1 module (vector) for cover page.
- [x] Replace "Spark" with "Particle"
- [x] Text for all sections

# Community Updates

Update these threads when P1, PØ datasheets are released.
- [x] https://community.particle.io/t/p1-dac-spi-pins/11936/3

**Comment by technobly** [comment]
When I edit the main post such as right now, I will add a new comment here for visibility.  I'm also updating all datasheets to point back to this known errata today.

**Comment by technobly** [comment]
Just changed this info in the P1 Datasheet Errata (SETUP -> RESET).

From:

```
Pinout image 3, SETUP button pin is 34 (MICRO_RST_N), not 26.
```

To:

```
Pinout image 3, RESET button pin is 34 (MICRO_RST_N), not 26.
```

**Comment by technobly** [comment]
Add electrical specification note for Photon/P1/Electron:

```
DAC output limits: min resistive load is 5k ohms, and max capacitive load is 50pF.
```

**Comment by kennethlimcp** [comment]
Electron - pinout pdf needs clarification - https://github.com/spark/docs/issues/310

**Comment by technobly** [comment]
Electron Datasheet Block Diagram error.

> Rework block diagram to remove the dot-junction for VUSB and STM32F205, they are not connected.  Only the two data lines are connected.  https://docs.particle.io/datasheets/electron-datasheet/#block-diagram

**Comment by technobly** [comment]
Changed requirement for update to BT COEX pins section:

> <s>Update BT COEX section with link to example of how to control as GPIO, or add a note as note supported.</s> Remove reference to using BT COEX pins as GPIO, this is not currently practical.

**Comment by technobly** [comment]
Added an Electron Datasheet v003 list (some carried over from v002)
- How to power the Electron without a battery.
- Describe the usage of the VBAT to 3V3 bridge on the bottom
- Electron Charging LED: But what is the "appropriate firmware command"? #326
- Change Vin and Iin parameters to Vvin and Ivin to be more clear

**Comment by technobly** [comment]
Added more info to: 
- Describe the usage of the VBAT to 3V3 bridge on the bottom.

**Comment by technobly** [comment]
Added to the Electron Datasheet v003 list:
- Fix and clarify pin descriptions https://github.com/spark/docs/pull/399 (make sure to review P1 and Photon datasheets as well)

**Comment by monkbroc** [comment]
Added to Electron Datasheet list: all 64kb of EEPROM page 2 is used

**Comment by monkbroc** [comment]
Added to Photon datasheet: rename device_id to device_code in DCT and add device_id

**Comment by technobly** [comment]
Added to the Electron Datasheet v003 list:
- v002 of the Pinout PDF has an error in the lower left of the Legend, UART4 and UART5 should be Serial4 and Serial5, not Serial2 and Serial3.

**Comment by technobly** [comment]
### P1 Datasheet (v006) - released... other pending P1 changes slated for v007 now.
- [x] Update P1 pin listing: TESTMODE pin 33 (PA8), connected to MCO1 by default, outputs 32kHz clock for WICED powersave mode - currently unsupported for user control.

**Comment by technobly** [comment]
Added to: 

# P1 Datasheet (v007)
- CAN bus pins should be noted as 3.3V tolerant (technically they are 5V tolerant on the RX but since you wouldn't operate them with a 5V transceiver it's proper to classify them as 3.3V)

# Photon Datasheet (v014)
- CAN bus pins should be noted as 3.3V tolerant (technically they are 5V tolerant on the RX but since you wouldn't operate them with a 5V transceiver it's proper to classify them as 3.3V)

# Electron Datasheet (v003)
- CAN bus pins should be noted as 3.3V tolerant (technically they are 5V tolerant on the RX but since you wouldn't operate them with a 5V transceiver it's proper to classify them as 3.3V)
- Memory Map: for v0.6.0-rc.1 and later has 3 system parts and re-ordering (1,2,3 is now 2,1,3).

**Comment by technobly** [comment]
## Added to Photon Datasheet (v014)
- Add warning about powering the Photon from long wires on USB and VIN, and give advice on what components can be added externally to mitigate this.  From Richtek datasheet:

> When a ceramic capacitor is used at the input and the power is supplied by a wall adapter through long wires, a load step at the output can induce ringing at the input, VIN. At best, this ringing can couple to the output and be mistaken as loop instability. At worst, a sudden inrush of current through the long wires can potentially cause a voltage spike at VIN large enough to damage the part

**Comment by technobly** [comment]
## Added to Electron Datasheet (v003)
- ERROR in Operating Current (Cellular OFF) IINavg 2-15mA, it should be IINavg 47-50mA

**Comment by technobly** [comment]
Pulled two changes into a separate release (v003), the rest are going into (v004):

# Electron Datasheet (v003)
- [x] Fix and clarify pin descriptions https://github.com/spark/docs/pull/399 (make sure to review P1 and Photon datasheets as well)
- [x] ERROR in Operating Current (Cellular OFF) IINavg 2-15mA, it should be IINavg 47-50mA

**Comment by technobly** [comment]
Electron Datasheet v003 has been released :)
https://docs.particle.io/datasheets/electron-datasheet/

**Comment by technobly** [comment]
Photon Datasheet (v014)
- [x] Updated list of Mating Connectors

Electron Datasheet (v003)
- [x] Updated list of Mating Connectors

and released!

**Comment by technobly** [comment]
Added item for P1 Datasheet v007 changes:
- Add note to clarify why MICRO_SPI1_SS is not hooked up to DAC/A6 (PA4) https://github.com/spark/docs/issues/469

**Comment by technobly** [comment]
Added items for P1 Datasheet v007:
- Add new spare pin P1S6 to pinout, PWM list, pin description, update TESTMODE description, etc.. https://github.com/spark/firmware/pull/1120
- update DCT Layout https://docs.particle.io/datasheets/p1-datasheet/#dct-layout notably adding radio_flags, and any other new sections.

Added item for Photon Datasheet v015:
- update DCT Layout https://docs.particle.io/datasheets/photon-datasheet/#dct-layout notably adding radio_flags, and any other new sections.

Added item for Electron Datasheet v004:
- update DCD Layout https://docs.particle.io/datasheets/electron-datasheet/#dcd-layout notably adding radio_flags, and any other new sections.

**Comment by technobly** [comment]
Bumped Electron Datasheet (v004) changes to (v005)

Added:

# Electron Datasheet (v004)
- Replace some copy/paste errors in STM32 part number in Electron datasheet copied from Photon datasheet.  Replace all STM32F205RGY6 with STM32F205RGT6.
- Add full STM32F205RGT6 part number to every mention of STM32 in datasheet.

**Comment by technobly** [comment]
### Electron Datasheet (v004) Released!

https://docs.particle.io/datasheets/electron-datasheet/

**Comment by technobly** [comment]
Added todo item for all datasheets:

- Replace STM32 pin names with Particle/Wiring API names to keep everything intuitive and high level.  Leave STM32 pin numbers for deep dives. #545

**Comment by technobly** [comment]
Added error for P1 datasheet:

- JTAG pin P1 module number is wrong.  "D4	JTAG_TDO PB3 54 MICRO_JTAG_TDO Floating" should be "D4 JTAG_TDO PB3 52 MICRO_JTAG_TDO Floating"  (54 -> 52)

**Comment by ghost** [comment]
The Richtek text in "Add warning about powering the Photon from long wires on USB and VIN" is a reference to [Linear AN-88](http://cds.linear.com/docs/en/application-note/an88f.pdf), but other than as a passing reference that topic seems to be out of scope for this datasheet...

**Comment by technobly** [comment]
@kdhooper thanks for the Linear AN-88 link, that's a nice reference.  May I ask why you propose it is out of scope for this datasheet? (the Photon's, and P1's if using a similar SMPS as the Photon's)

**Comment by ghost** [comment]
This issue is not specific to the Richtek part and has more to do with the design of the entire product than the Photon itself.

**Comment by technobly** [comment]
@kdhooper we do have a product creator guide which might be the scope you are referring to, but many people will look at the datasheet before the rest of the docs.  I will include some helpful text in the datasheet Power section about this for system integrators.

**Comment by technobly** [comment]
### p1-datasheet-v008, photon-datasheet-v015 and electron-datasheet-v005 Released!  
All known errata incorporated into datasheets :)

**Comment by technobly** [comment]
### P1 Datasheet (v009) Released
- [x] Added part number for 1MB external SPI flash (MX25L8006E)

**Comment by monkbroc** [comment]
Added note to reword the pricing statement at the top of the P1 datasheet

**Comment by dmiddlecamp** [comment]
E Series Datasheet:

* Missing documentation on unpopulated external flash, necessary info:
  * D5 is chip select pin for that flash
  * The flash uses SPI1

**Comment by technobly** [comment]
### Photon Datasheet (v016)
- [x] Updated External Coexistence Interface section (currently unsupported)

### P1 Datasheet (v010)
- [x] Updated External Coexistence Interface section (currently unsupported)
