### ISSUE TITLE
Firmware docs 0.5.0

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot/docs#309]
New docs for 0.5.0
- [x] new SOS code for Stack overflow @m-mcgowan
- [x] cellular band API https://github.com/spark/firmware/pull/891 @technobly 
- [x] cellular data usage API https://github.com/spark/firmware/pull/866 @technobly 
- [x] cellular localIP https://github.com/spark/firmware/pull/850 @technobly 
- [x] Serial.availableForWrite() / Serial.blockOnOverrun() https://github.com/spark/firmware/pull/812 @avtolstoy #339 
- [x] `System.sleep(SLEEP_NETWORK_STANDBY)` @m-mcgowan
- [x] `System.sleep(pin, edge, duration)` on wakeup, connects to the cloud in `AUTOMATIC/SEMI-AUTOMATIC` mode. (Not when threading is enabled. To wait for the cloud to be reconnected, e.g. to publish immediately after waking, use `waitFor(Particle.connected)` @m-mcgowan
- [x] SPI Slave - https://github.com/spark/firmware/pull/882 @avtolstoy #338 
- [x] EEPROM emulation revamp - #323 https://github.com/spark/firmware/pull/871 @monkbroc 
- [x] long variable/function names compiler error - https://github.com/spark/firmware/pull/883 @monkbroc 
- [x] Publish NO_ACK - https://github.com/spark/firmware/pull/862 @m-mcgowan 
- [x] configurable keep alive - https://github.com/spark/firmware/pull/913 @m-mcgowan
- [x] serial parity - https://github.com/spark/docs/pull/317 
- [x] Application Watchdog - https://github.com/spark/firmware/pull/860 @m-mcgowan
- [x] measure and add Particle.keepAlive() data usage - https://github.com/spark/firmware/pull/913 @technobly
- [x] application softAP pages - https://github.com/spark/firmware/pull/906 @m-mcgowan
- [x] Timer.isActive() - https://github.com/spark/firmware/pull/950 @sergeuz 
  When the location of the docs for a feature is known, please link from the corresponding entry in `CHANGELOG.md` in the firmware repo.
